# Generated by Django 2.2.4 on 2019-09-21 04:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name=' product标题')),
                ('description', models.TextField(verbose_name='product详情描述')),
                ('productType', models.CharField(choices=[('Child', 'Child'), ('Nature', 'Nature'), ('People with disabilities', 'People with disabilities')], max_length=50, verbose_name='product类型')),
                ('price', models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True, verbose_name='product价格')),
                ('publishDate', models.DateTimeField(default=django.utils.timezone.now, max_length=20, verbose_name='Release')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='views')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'product',
                'ordering': ('-publishDate',),
            },
        ),
        migrations.CreateModel(
            name='ProductImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='Product/', verbose_name='product图片')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productImgs', to='productsApp.Product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'product图片',
                'verbose_name_plural': 'product图片',
            },
        ),
    ]
