# Generated by Django 2.2.4 on 2022-04-12 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-publishDate',), 'verbose_name': 'Theme', 'verbose_name_plural': 'Theme'},
        ),
        migrations.AlterModelOptions(
            name='productimg',
            options={'verbose_name': 'Theme photo', 'verbose_name_plural': 'Theme photo'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(verbose_name='Theme description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='productType',
            field=models.CharField(choices=[('Child', 'Child'), ('Nature', 'Nature'), ('People with disabilities', 'People with disabilities'), ('Covid', 'Covid')], max_length=50, verbose_name='Theme type'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=50, verbose_name=' Theme title'),
        ),
        migrations.AlterField(
            model_name='productimg',
            name='photo',
            field=models.ImageField(blank=True, upload_to='Product/', verbose_name='Theme photo'),
        ),
        migrations.AlterField(
            model_name='productimg',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productImgs', to='productsApp.Product', verbose_name='Theme'),
        ),
    ]
