# Generated by Django 2.2.4 on 2022-04-07 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactApp', '0004_auto_20191003_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='birth',
            field=models.DateField(default='2022-04-08', max_length=20, verbose_name='date of birth'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='edu',
            field=models.CharField(default='bachelor', max_length=5, verbose_name='Education Level'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='email',
            field=models.EmailField(max_length=30, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='experience',
            field=models.TextField(blank=True, null=True, verbose_name='experience'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='major',
            field=models.CharField(max_length=40, verbose_name='Major'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='personID',
            field=models.CharField(max_length=30, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='position',
            field=models.CharField(max_length=40, verbose_name='Apply'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='school',
            field=models.CharField(max_length=40, verbose_name='School'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='sex',
            field=models.CharField(default='Male', max_length=5, verbose_name='sex'),
        ),
    ]
