# Generated by Django 2.2.4 on 2019-09-23 23:17

import DjangoUeditor.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyNew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name=' News title')),
                ('description', DjangoUeditor.models.UEditorField(default='', verbose_name='内容')),
                ('newType', models.CharField(choices=[('Organization progress', 'Organization progress'), ('Social news', 'Social news'), ('Public Release', 'Public Release')], max_length=50, verbose_name='News type')),
                ('publishDate', models.DateTimeField(default=django.utils.timezone.now, max_length=20, verbose_name='Release')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='views')),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
                'ordering': ['-publishDate'],
            },
        ),
    ]
