# Generated by Django 2.2.4 on 2022-04-12 20:06

import DjangoUeditor.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('newsApp', '0002_mynew_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mynew',
            name='description',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='mynew',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='news/', verbose_name='Results figure'),
        ),
        migrations.AlterField(
            model_name='mynew',
            name='publishDate',
            field=models.DateTimeField(default=django.utils.timezone.now, max_length=20, verbose_name='Release time'),
        ),
        migrations.AlterField(
            model_name='mynew',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='views'),
        ),
    ]
