# Generated by Django 2.2.4 on 2022-04-12 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doc',
            options={'ordering': ['-publishDate'], 'verbose_name': 'Data', 'verbose_name_plural': 'Data'},
        ),
        migrations.AlterField(
            model_name='doc',
            name='file',
            field=models.FileField(blank=True, upload_to='Service/', verbose_name='File data'),
        ),
        migrations.AlterField(
            model_name='doc',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Data name'),
        ),
    ]
